version: '3'

services:

  # Postgres BD
  postgres:
    build: postgres/
    environment:
      - POSTGRES_USER=roiback
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=roiback_prod
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/shared/:/data/shared

  # API roiback
  api:
    build: python/
    command: sh /scripts/run_web.sh
    volumes:
      - ../../api:/app
      - ./python/scripts:/scripts
    env_file:
      - ./python/configs/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8090:5560"

  redis:
    build: redis/
    volumes:
      - ./redis/data:/data
      - ./redis/shared:/sharedfolder
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
